# Default values for kube-arbitrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: cc.cmu
  tag: 0.1
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi
conf: kube-system/scheduler-conf

